# Generated by Django 6.0.3 on 2026-03-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email professionnel')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('organisation', models.CharField(max_length=255, verbose_name='Organisation')),
                ('profile', models.CharField(choices=[('ipm', 'IPM / Mutuelle'), ('prestataire', 'Prestataire de soins (Médecin, Clinique, Pharmacie)'), ('patient', 'Patient / Assuré'), ('partenaire', 'Partenaire'), ('autre', 'Autre')], max_length=20, verbose_name='Profil')),
                ('message', models.TextField(blank=True, verbose_name='Besoin / message')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('contacted', 'Contactée'), ('done', 'Traitée')], default='new', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('notes', models.TextField(blank=True, verbose_name='Notes interne (admin)')),
            ],
            options={
                'verbose_name': 'Demande de démo',
                'verbose_name_plural': 'Demandes de démo',
                'ordering': ['-created_at'],
            },
        ),
    ]
