# Generated by Django 6.0.3 on 2026-03-15 18:55

from django.db import migrations, models


def create_default_config(apps, schema_editor):
    DemoRequestNotificationConfig = apps.get_model("core", "DemoRequestNotificationConfig")
    if not DemoRequestNotificationConfig.objects.exists():
        DemoRequestNotificationConfig.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_demo_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequestNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_emails', models.TextField(blank=True, help_text="Une adresse email par ligne. Laissez vide pour utiliser les adresses définies dans la variable d'environnement REMEDY_DEMO_NOTIFICATION_EMAILS.", verbose_name='Adresses qui reçoivent les nouvelles demandes')),
                ('send_copy_to_client', models.BooleanField(default=False, help_text='Si coché, la personne qui soumet la demande reçoit un email de confirmation.', verbose_name='Envoyer une copie de confirmation au client')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Configuration des notifications démo',
                'verbose_name_plural': 'Configuration des notifications démo',
            },
        ),
        migrations.RunPython(create_default_config, migrations.RunPython.noop),
    ]
