# Generated by Django 6.0.3 on 2026-03-15 18:59

from django.db import migrations, models


def create_default_testimonials(apps, schema_editor):
    Testimonial = apps.get_model("core", "Testimonial")
    if Testimonial.objects.exists():
        return
    Testimonial.objects.bulk_create([
        Testimonial(
            author="Aminata Diallo",
            role_or_organisation="Directrice des opérations, IPM Horizon Santé",
            quote="Remedi a transformé notre gestion quotidienne. Nous avons réduit nos délais de traitement et nos prestataires sont ravis de la transparence.",
            order=0,
            is_active=True,
        ),
        Testimonial(
            author="Dr. Ousmane Fall",
            role_or_organisation="Clinique de l'Espoir",
            quote="Je soumets mes factures en ligne en quelques clics et je suis payé beaucoup plus rapidement qu'avant. Un vrai gain de temps.",
            order=1,
            is_active=True,
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_demo_notification_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name='Auteur')),
                ('role_or_organisation', models.CharField(help_text="Ex. : Directrice des opérations, IPM Horizon Santé — ou : Clinique de l'Espoir", max_length=255, verbose_name='Fonction ou organisation')),
                ('quote', models.TextField(verbose_name='Citation / avis')),
                ('order', models.PositiveIntegerField(default=0, help_text="Plus le nombre est petit, plus l'avis apparaît en premier.", verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Avis / Témoignage',
                'verbose_name_plural': 'Avis / Témoignages',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RunPython(create_default_testimonials, migrations.RunPython.noop),
    ]
