# Generated by Django 6.0.3 on 2026-03-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_emails', models.TextField(verbose_name='Destinataires')),
                ('from_email', models.CharField(max_length=255, verbose_name='Expéditeur')),
                ('subject', models.CharField(max_length=500, verbose_name='Objet')),
                ('body_plain', models.TextField(blank=True, verbose_name='Corps (texte)')),
                ('body_html', models.TextField(blank=True, verbose_name='Corps (HTML)')),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('failed', 'Échec')], max_length=20, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('email_type', models.CharField(blank=True, max_length=50, verbose_name='Type')),
                ('related_ref', models.CharField(blank=True, help_text='Ex. demorequest:5, claim:123', max_length=255, verbose_name='Référence')),
            ],
            options={
                'verbose_name': "Log d'email",
                'verbose_name_plural': "Logs d'emails",
                'ordering': ['-sent_at'],
            },
        ),
    ]
