# Generated by Django 6.0.2 on 2026-02-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_remove_coveragerule_ipm_finalize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipm',
            options={'ordering': ['name'], 'verbose_name': 'IPM', 'verbose_name_plural': 'IPMs'},
        ),
        migrations.AddField(
            model_name='ipm',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse siège'),
        ),
        migrations.AddField(
            model_name='ipm',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='ipm',
            name='code',
            field=models.CharField(blank=True, help_text='Identifiant court pour référence', max_length=30, unique=True, verbose_name='Code (ex: SANTEPLUS)'),
        ),
        migrations.AddField(
            model_name='ipm',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='ipm',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='ipm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='care_date',
            field=models.DateField(blank=True, help_text='Date des soins', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='N° facture / référence', max_length=80),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('LOCKED', 'Verrouillée'), ('PATIENT_CONFIRMED', 'Confirmée patient'), ('READY_FOR_PAYMENT', 'Prête au paiement'), ('DISPUTED', 'Contestée'), ('BLOCKED', 'Bloquée')], default='DRAFT', max_length=25),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Raison sociale / Nom'),
        ),
    ]
