# Generated by Django 6.0.2 on 2026-02-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_ipm_enrich_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipm',
            name='code',
            field=models.CharField(blank=True, help_text='Identifiant court pour référence', max_length=30, null=True, unique=True, verbose_name='Code (ex: SANTEPLUS)'),
        ),
    ]
