# Generated by Django 6.0.2 on 2026-02-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_ipm_code_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Libellé')),
                ('code', models.CharField(blank=True, help_text='Ex: VIREMENT, CHEQUE', max_length=30, null=True, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Moyen de paiement',
                'verbose_name_plural': 'Moyens de paiement',
                'ordering': ['name'],
            },
        ),
    ]
