# Generated by Django 6.0.2 on 2026-02-20 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_add_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile money'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('OTHER', 'Autre')], default='OTHER', help_text='Définit les champs à renseigner (tél, IBAN, bénéficiaire…)', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(blank=True, help_text='Ex: VIREMENT, MOBILE_MONEY', max_length=30, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.CreateModel(
            name='IPMPaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='N° téléphone (mobile money)')),
                ('iban', models.CharField(blank=True, max_length=40, verbose_name='IBAN')),
                ('bank_name', models.CharField(blank=True, max_length=120, verbose_name='Banque')),
                ('payee_name', models.CharField(blank=True, max_length=120, verbose_name="À l'ordre de (chèque)")),
                ('reference_notes', models.CharField(blank=True, max_length=255, verbose_name='Référence / précisions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ipm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='claims.ipm')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipm_options', to='claims.paymentmethod')),
            ],
            options={
                'verbose_name': 'Moyen de paiement IPM',
                'verbose_name_plural': 'Moyens de paiement IPM',
                'ordering': ['payment_method__name'],
                'constraints': [models.UniqueConstraint(fields=('ipm', 'payment_method'), name='unique_ipm_payment_option')],
            },
        ),
    ]
