# Generated by Django 6.0.2 on 2026-02-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_payment_method_type_and_ipm_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ipmpaymentoption',
            name='unique_ipm_payment_option',
        ),
        migrations.AddField(
            model_name='claim',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date suppression'),
        ),
        migrations.AddField(
            model_name='claim',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé (soft)'),
        ),
        migrations.AddField(
            model_name='ipmpaymentoption',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date suppression'),
        ),
        migrations.AddField(
            model_name='ipmpaymentoption',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé (soft)'),
        ),
        migrations.AddConstraint(
            model_name='ipmpaymentoption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('ipm', 'payment_method'), name='unique_ipm_payment_option'),
        ),
    ]
