# Generated by Django 6.0.2 on 2026-02-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_soft_delete_claim_ipmpaymentoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipm',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date suppression'),
        ),
        migrations.AddField(
            model_name='ipm',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé (soft)'),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='code',
            field=models.CharField(blank=True, help_text='Identifiant court pour référence', max_length=30, null=True, verbose_name='Code (ex: SANTEPLUS)'),
        ),
        migrations.AlterField(
            model_name='ipm',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Raison sociale / Nom'),
        ),
        migrations.AddConstraint(
            model_name='ipm',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_ipm_name_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='ipm',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('code', ''), _negated=True)), fields=('code',), name='unique_ipm_code_not_deleted'),
        ),
    ]
