# Generated by Django 6.0.2 on 2026-02-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0012_add_deleted_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient / Bénéficiaire', 'verbose_name_plural': 'Patients / Bénéficiaires'},
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Format JJ/MM/AAAA', null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('OTHER', 'Autre')], max_length=10, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.CharField(blank=True, help_text='CNI, passeport, etc.', max_length=50, verbose_name="N° pièce d'identité"),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='beneficiary_type',
            field=models.CharField(choices=[('TITULAIRE', 'Titulaire (adhérent principal)'), ('CONJOINT', 'Conjoint(e)'), ('ENFANT', 'Enfant'), ('AYANT_DROIT', 'Ayant droit')], default='TITULAIRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='member_number',
            field=models.CharField(max_length=80, verbose_name='N° membre / matricule'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Téléphone'),
        ),
    ]
