# Generated by Django 6.0.2 on 2026-02-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_patient_enrich_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_document',
            field=models.FileField(blank=True, help_text='Recto ou recto-verso de la CNI, passeport, etc.', null=True, upload_to='patient_kyc/%Y/%m/', verbose_name="Photo / scan pièce d'identité (KYC)"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.CharField(blank=True, help_text='Numéro de CNI ou passeport. Utilisé pour la recherche chez les providers.', max_length=50, verbose_name="N° CNI / pièce d'identité"),
        ),
    ]
