# Generated by Django 6.0.2 on 2026-02-20 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0014_patient_kyc_id_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date suppression')),
                ('name', models.CharField(max_length=120, verbose_name='Raison sociale / Nom')),
                ('code', models.CharField(blank=True, help_text='Identifiant court pour référence', max_length=30, null=True, verbose_name='Code')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Ville')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Hôpital / Pharmacie',
                'verbose_name_plural': 'Hôpitaux / Pharmacies',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_hospital_name_not_deleted'), models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('code', ''), _negated=True)), fields=('code',), name='unique_hospital_code_not_deleted')],
            },
        ),
    ]
