# Generated by Django 6.0.2 on 2026-02-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0015_add_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='dispute_reason',
            field=models.TextField(blank=True, verbose_name='Motif de contestation (patient)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='establishment_type',
            field=models.CharField(choices=[('HOSPITAL', 'Hôpital / Clinique'), ('PHARMACY', 'Pharmacie')], default='HOSPITAL', max_length=20, verbose_name='Type'),
        ),
    ]
