# Generated by Django 6.0.2 on 2026-02-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0016_hospital_type_and_dispute_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=20, unique=True, verbose_name='Canal')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Paramètres (JSON)')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier test')),
                ('last_test_error', models.TextField(blank=True, verbose_name='Erreur dernier test')),
            ],
            options={
                'verbose_name': 'Configuration notification',
                'verbose_name_plural': 'Configurations notifications',
                'ordering': ['channel'],
            },
        ),
    ]
