# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0017_notification_channel_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='claim',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='notification_logs', to='claims.claim'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='target',
            field=models.CharField(help_text='Email, numéro de téléphone, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name="Message d'erreur (si échec)"),
        ),
    ]
