# Generated by Django 6.0.2 on 2026-02-20 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0018_notification_log_error_and_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentPaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date suppression')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='N° téléphone (mobile money)')),
                ('iban', models.CharField(blank=True, max_length=40, verbose_name='IBAN')),
                ('bank_name', models.CharField(blank=True, max_length=120, verbose_name='Banque')),
                ('payee_name', models.CharField(blank=True, max_length=120, verbose_name="À l'ordre de (chèque)")),
                ('reference_notes', models.CharField(blank=True, max_length=255, verbose_name='Référence / précisions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='claims.hospital')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_options', to='claims.paymentmethod')),
            ],
            options={
                'verbose_name': 'Moyen de paiement établissement',
                'verbose_name_plural': 'Moyens de paiement établissement',
                'ordering': ['payment_method__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('hospital', 'payment_method'), name='unique_establishment_payment_option')],
            },
        ),
    ]
