# Generated by Django 6.0.2 on 2026-02-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date suppression'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé (soft)'),
        ),
    ]
