# Generated by Django 6.0.2 on 2026-02-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='organisation_name',
            field=models.CharField(blank=True, help_text="Nom de l'hôpital, clinique ou pharmacie (affiché sur la page de validation patient).", max_length=150, verbose_name="Nom de l'organisation"),
        ),
    ]
