# Generated by Django 6.0.2 on 2026-02-20 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_organisation_name'),
        ('claims', '0015_add_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Établissement de soins (prestataire). Affiché sur la page de validation patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='claims.hospital', verbose_name='Hôpital / Pharmacie'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='organisation_name',
            field=models.CharField(blank=True, help_text='Ancien champ texte ; préférer l’objet Hôpital si renseigné.', max_length=150, verbose_name="Nom de l'organisation (legacy)"),
        ),
    ]
