# Generated by Django 6.0.2 on 2026-02-23 04:18

import django.db.models.deletion
from django.db import migrations, models


def fill_ipm_from_ipm_name(apps, schema_editor):
    """Remplit StaffProfile.ipm à partir de ipm_name pour les enregistrements existants."""
    StaffProfile = apps.get_model("accounts", "StaffProfile")
    IPM = apps.get_model("claims", "IPM")
    for profile in StaffProfile.objects.filter(ipm__isnull=True).exclude(ipm_name=""):
        name = (profile.ipm_name or "").strip()
        if not name:
            continue
        ipm = IPM.objects.filter(name__iexact=name).first()
        if ipm:
            profile.ipm = ipm
            profile.save(update_fields=["ipm"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_hospital_fk'),
        ('claims', '0019_establishment_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='ipm',
            field=models.ForeignKey(blank=True, help_text='Institution de prévoyance maladie (pour rôle IPM Admin). Utilisé pour le périmètre des dossiers et patients.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to='claims.ipm', verbose_name='IPM'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='ipm_name',
            field=models.CharField(blank=True, help_text='Ancien champ texte ; utiliser le champ IPM (FK) à la place.', max_length=120, verbose_name='Nom IPM (legacy)'),
        ),
        migrations.RunPython(fill_ipm_from_ipm_name, noop),
    ]
