# Generated by Django 6.0.2 on 2026-02-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_staffprofile_ipm_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='ipm_name',
            field=models.CharField(blank=True, help_text="Nom de l'IPM (affiché). Synchronisé avec la FK IPM si elle est renseignée.", max_length=120, verbose_name='Nom IPM'),
        ),
    ]
