from django.urls import path

from .views import (
    api_coverage,
    claim_create,
    claim_delete,
    claim_detail,
    claim_edit,
    claim_list,
    category_create,
    category_edit,
    category_list,
    category_seed_defaults,
    coverage_rule_create,
    coverage_rule_edit,
    coverage_rule_list,
    hospital_create,
    hospital_create_ajax,
    hospital_delete,
    hospital_edit,
    hospital_list,
    ipm_create,
    ipm_create_ajax,
    ipm_delete,
    ipm_edit,
    ipm_list,
    my_establishment_payment_options,
    notification_edit,
    notification_list,
    notification_test,
    payment_method_create,
    payment_method_edit,
    payment_method_list,
    patient_create,
    patient_edit,
    patient_list,
    patient_verify,
    plan_create,
    plan_edit,
    plan_list,
    user_create,
    user_delete,
    user_edit,
    user_list,
)

urlpatterns = [
    path("", claim_list, name="claim_list"),
    path("api/coverage/", api_coverage, name="api_coverage"),
    path("create/", claim_create, name="claim_create"),
    path("<int:claim_id>/edit/", claim_edit, name="claim_edit"),
    path("<int:claim_id>/delete/", claim_delete, name="claim_delete"),
    path("<int:claim_id>/", claim_detail, name="claim_detail"),
    path("verify/<str:token>/", patient_verify, name="patient_verify"),
    # Patients
    path("patients/", patient_list, name="patient_list"),
    path("patients/create/", patient_create, name="patient_create"),
    path("patients/<int:patient_id>/edit/", patient_edit, name="patient_edit"),
    # IPMs
    path("ipms/", ipm_list, name="ipm_list"),
    path("ipms/create/", ipm_create, name="ipm_create"),
    path("ipms/create-ajax/", ipm_create_ajax, name="ipm_create_ajax"),
    path("ipms/<int:ipm_id>/edit/", ipm_edit, name="ipm_edit"),
    path("ipms/<int:ipm_id>/delete/", ipm_delete, name="ipm_delete"),
    # Hôpitaux / Pharmacies
    path("hospitals/", hospital_list, name="hospital_list"),
    path("hospitals/create/", hospital_create, name="hospital_create"),
    path("hospitals/create-ajax/", hospital_create_ajax, name="hospital_create_ajax"),
    path("hospitals/<int:hospital_id>/edit/", hospital_edit, name="hospital_edit"),
    path("hospitals/<int:hospital_id>/delete/", hospital_delete, name="hospital_delete"),
    path("my-establishment/payment-options/", my_establishment_payment_options, name="my_establishment_payment_options"),
    # Coverage Plans (Formules)
    path("formules/", plan_list, name="plan_list"),
    path("formules/create/", plan_create, name="plan_create"),
    path("formules/<int:plan_id>/edit/", plan_edit, name="plan_edit"),
    # Coverage Rules
    path("coverage-rules/", coverage_rule_list, name="coverage_rule_list"),
    path("coverage-rules/create/", coverage_rule_create, name="coverage_rule_create"),
    path("coverage-rules/<int:rule_id>/edit/", coverage_rule_edit, name="coverage_rule_edit"),
    # Categories
    path("categories/", category_list, name="category_list"),
    path("categories/seed-defaults/", category_seed_defaults, name="category_seed_defaults"),
    path("categories/create/", category_create, name="category_create"),
    path("categories/<int:category_id>/edit/", category_edit, name="category_edit"),
    # Moyens de paiement
    path("payment-methods/", payment_method_list, name="payment_method_list"),
    path("payment-methods/create/", payment_method_create, name="payment_method_create"),
    path("payment-methods/<int:payment_method_id>/edit/", payment_method_edit, name="payment_method_edit"),
    # Users
    path("users/", user_list, name="user_list"),
    path("users/create/", user_create, name="user_create"),
    path("users/<int:user_id>/edit/", user_edit, name="user_edit"),
    path("users/<int:user_id>/delete/", user_delete, name="user_delete"),
    # Notifications (canaux : Email, SMS, WhatsApp)
    path("notifications/", notification_list, name="notification_list"),
    path("notifications/<str:channel_code>/test/", notification_test, name="notification_test"),
    path("notifications/<str:channel_code>/", notification_edit, name="notification_edit"),
]
